# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
