# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170728_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba'),
        ),
    ]
